// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0W6XNhBeOJimP908lAne5tr6ZKY4Fvw',
    appId: '1:324315779344:web:42bf4063328ce24ea49595',
    messagingSenderId: '324315779344',
    projectId: 'social-media-auth-sample',
    authDomain: 'social-media-auth-sample.firebaseapp.com',
    storageBucket: 'social-media-auth-sample.appspot.com',
    measurementId: 'G-4DGJC5QPEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhUSpXHDKN7udQVJ3D_tu2bvVSKONOCA',
    appId: '1:324315779344:android:1f5231fd1ec9f6f8a49595',
    messagingSenderId: '324315779344',
    projectId: 'social-media-auth-sample',
    storageBucket: 'social-media-auth-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEbMArn0XtljwqIx6eD3prlGdJB8Rctjw',
    appId: '1:324315779344:ios:f29102680277779ca49595',
    messagingSenderId: '324315779344',
    projectId: 'social-media-auth-sample',
    storageBucket: 'social-media-auth-sample.appspot.com',
    androidClientId: '324315779344-0bcfdsg5mcpqr03dasut4q5hqpnc0ekc.apps.googleusercontent.com',
    iosClientId: '324315779344-87vdovmb78sgtmlosq441q10hgeikoes.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0W6XNhBeOJimP908lAne5tr6ZKY4Fvw',
    appId: '1:324315779344:web:3290418124b16fcda49595',
    messagingSenderId: '324315779344',
    projectId: 'social-media-auth-sample',
    authDomain: 'social-media-auth-sample.firebaseapp.com',
    storageBucket: 'social-media-auth-sample.appspot.com',
    measurementId: 'G-QDW7PXT3N2',
  );
}
